# Generated by Django 4.0.3 on 2022-03-08 10:05

from django.db import migrations, models
import sendresume.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('cv', models.FileField(blank=True, null=True, upload_to='uploads/cv', validators=[sendresume.validators.validate_file_size], verbose_name='CV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='Read By Admin')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'List of Resumes',
            },
        ),
    ]
